### PR TITLE
Fix/add timestamp to testsuites xml

### PR DESCRIPTION
**Pull request by albertpuente**
Implemented simple timestamp patching on the incoming xml (xunit) files in the golang client. The timestamp is computed upon reception of the files.

Unmarshalling the previously loaded xunit instead of replacing strings produced wrongly formatted system-output fields within the xml file.

### CODE REVIEW

**Comment by metmajer** [comment]
@braisvq1996 no approvals without test cases please

**Comment by metmajer** [comment]
@albertpuente I suggest you separate the file writing from the actual replacement operation. this way, you do not need to consider the file operations in the test

**Comment by albertpuente** [comment]
Added test action and implementation, but something is still failing for windows, mac despite working locally...

**Comment by metmajer** [comment]
@albertpuente error reads as: "run-detectors: unable to find an interpreter for /tmp/go-build3200069865/b160/test.test.exe" -> wrong file name

**Pull request merged**
